Pages/Haulage/PlantHire.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RJHWebsite.Pages.Haulage
{
    public class PlantHireModel : PageModel
    {
        public string PlantType { get; set; }
        public void OnGet([FromQuery(Name = "plant-type")] string plantType)
        {
            PlantType = plantType;
        }
    }
}

Pages/Haulage/TipperHire.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace RJHWebsite.Pages.Haulage
{
    public class TipperHireModel : PageModel
    {
        public class Tippers
        {
            public string TipperName { get; set; }
            public string DeliveryInfo { get; set; }
            public string Capabilities { get; set; }
            public string ImageName { get; set; }
            public string ImageDescription { get; set; }
        }
        public List<Tippers> AllTippers { get; set; }
        public string TipperType { get; set; }
        public void OnGet([FromQuery(Name = "tipper-type")] string tipperType)
        {
            string tipperJson = System.IO.File.ReadAllText("tippers-v1.0.json").ToString();
            AllTippers = JsonConvert.DeserializeObject<List<Tippers>>(tipperJson);
            TipperType = tipperType;
        }
    }
}

Pages/Shared/Components/NewsSnippet/NewsSnippetViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RJHWebsite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace RJHWebsite.Pages.Shared.Components.NewsSnippet
{
    public class NewsSnippetViewComponent : ViewComponent
    {
        public class NewsSnippetViewModel
        {
            public List<NewsInformationModel> NewsInformationModel { get; set; }
            public int SnippetTypeEnum { get; set; }
            public int? NumberOfArticles { get; set; }
            public int CssStyleEnum { get; set; }
            public string Title { get; set; }
        }
        public IViewComponentResult Invoke(int snippetTypeEnum, int? numberOfArticles, int cssStyleEnum, string title, string currentNewsPage)
        {
            string newsJson = File.ReadAllText("news-articles-v1.0.json").ToString();
            List<NewsInformationModel> newsInfo = JsonConvert.DeserializeObject<List<NewsInformationModel>>(newsJson);
            newsInfo = newsInfo.OrderByDescending(r=>Convert.ToDateTime(r.PublishedDate)).Where(r=>r.Title != currentNewsPage).ToList();
            if (numberOfArticles != null)
            {
                newsInfo = newsInfo.Take((int)numberOfArticles).ToList();
            }
            NewsSnippetViewModel viewmodel = new NewsSnippetViewModel()
            {
                NewsInformationModel = newsInfo,
                NumberOfArticles = numberOfArticles,
                SnippetTypeEnum = snippetTypeEnum,
                CssStyleEnum = cssStyleEnum,
                Title = title,
            };
            return View("NewsSnippet", viewmodel);
        }
    }
}

Pages/Shared/Components/OtherPagesSnippet/OtherPagesSnippetViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RJHWebsite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace RJHWebsite.Pages.Shared.Components.OtherPagesSnippet
{
    public class OtherPagesSnippetViewComponent:ViewComponent
    {
        public class OtherPagesSnipperViewModel
        {
            public List<SiteStructureModel> SiteStructure { get; set; }
            public int SnippetTypeEnum { get; set; }
            public string Title { get; set; }
            public int CssStyleEnum { get; set; }
        }
        public IViewComponentResult Invoke(OtherPagesSnippetModel model)
        {
            string siteStructureJson = File.ReadAllText("site-structure-v1.0.json").ToString();
            OtherPagesSnipperViewModel jsonResult = JsonConvert.DeserializeObject<OtherPagesSnipperViewModel> (siteStructureJson);
            jsonResult.SiteStructure = jsonResult.SiteStructure.Where(r => r.PageLevel == 2 && r.ParentPageName.ToLower() == model.ParentPage.ToLower() && r.PageName.ToLower() != model.CurrentPage.ToLower()).ToList();
            return View("OtherPagesSnippet", new OtherPagesSnipperViewModel()
            {
                SnippetTypeEnum = model.SnippetTypeEnum,
                SiteStructure = jsonResult.SiteStructure,
                Title = model.Title,
                CssStyleEnum = model.CssStyleEnum
            });
        }
    }
}

Pages/Shared/Components/TileSnippet/TileSnippetViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RJHWebsite.Pages.Shared.Components.TileSnippet
{
    public class TileSnippetViewComponent : ViewComponent
    {
        public class TileSnippetViewModel
        {
            public string ImagePath { get; set; }
            public string ImageDescription { get; set; }
            public string Title { get; set; }
            public string ButtonText { get; set; }
            public string ButtonLink { get; set; }
            public int TileStyleEnum { get; set; }
        }
        public IViewComponentResult Invoke(TileSnippetViewModel viewmodel)
        {
            return View("TileSnippet", viewmodel);
        }
    }
}

Pages/Haulage/HaulageServices.cshtml
@page "/haulage-services"
@using RJHWebsite.Enums
@using System.Configuration
@{
    ViewBag.NavButtonNames = "haulage-services-nav-btn";
    ViewBag.Title = "Road and Rail Haulage Services";
}
@section head{
    <meta name='description' content="Being the leader of road and rail haulage services in East Anglia and beyond, we are able to efficiently and confidently undertake any haulage tasks." />
}
<partial name='partials/_image' model='new RJHWebsite.Models.ImageModel(){ ImageClassName = "main-img",ImageName="all-rory-lorries", ImageDescription = "Fleet of some of the lorries working for Rory"}'/>
<div class="page-name">
    <h1>Haulage Services</h1>
</div>
<div class="page-with-sidebar-container">
    <div class="page-with-sidebar-main">
        <div class="left-right-padding">
            <div class="row">
                <nav aria-label="breadcrumb" class="mt-4">
                    <ol class="breadcrumb pl-0">
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["Home"]">Home</a></li>
                        <li class="breadcrumb-item active"><a href="#">Haulage</a></li>
                    </ol>
                    <hr class="mb-0" />
                </nav>
            </div>
            <div class="top-bottom-padding">
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_roadhaulageservicestile" model="@(int)TileStyles.SquareZoom" />
                </div>
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_railhaulageservicestile" model="@(int)TileStyles.SquareZoom" />
                </div>
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_nontippingconveyorfloortile" model="@(int)TileStyles.SquareZoom" />
                </div>
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_plantservicestile" model="@(int)TileStyles.SquareZoom" />
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar bg-light-light-grey">
        @await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
        {
            SnippetTypeEnum = (int)Enums.SnippetTypes.Sidebar,
            CurrentPage = "",
            ParentPage = "construction",
            CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.LightGrey,
            Title = "Explore Our Construction Services"
        })

        @await Component.InvokeAsync("NewsSnippet", new { snippetTypeEnum = (int)Enums.SnippetTypes.Sidebar, numberOfArticles = 2, cssStyleEnum = (int)Enums.CssStyles.LightGrey })
    </div>
</div>

@await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
{
    SnippetTypeEnum = (int)Enums.SnippetTypes.FullBottomBar,
    CurrentPage = "",
    ParentPage = "construction",
    CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.Dark,
    Title = "Explore Our Construction Services"
})
<div class="bg-dark-red">
    <div class="left-right-padding top-bottom-padding">
        <div class="row">
            <partial name="partials/sliders/_standardsandpartnerssliders" model="@(int)Enums.Variations.Variation3" />
        </div>
    </div>
</div>
@section scripts {
    <script>
        $('#road-and-rail-haulage-nav-btn').css('color', 'black').css('font-weight', 'bold');
    </script>
}

Pages/Haulage/PlantHire.cshtml
@page "/plant-services/plant-hire"
@model RJHWebsite.Pages.Haulage.PlantHireModel
@using RJHWebsite.Pages.Shared.Components.TileSnippet;
@using RJHWebsite.Enums
@using System.Configuration
@{
    ViewBag.Title = "Plant Hire";
    ViewBag.NavButtonNames = "haulage-services-nav-btn,plant-hire-nav-btn";
}
@section head{
    if (Model.PlantType != null)
    {
        <meta name="robots" content="noindex">
    }
    <meta name='description' content='Rory J Holbrook Ltd has a varying range of plant and equipment available for hire, both short term and long term.' />
    <meta name='keywords' content='Doosan, liugong, jcb, 360, digger, machine, screener, crusher, loading shovel, teleporter' />
}
<div class="main-img">
    <partial name='partials/_image' model='new RJHWebsite.Models.ImageModel(){ ImageClassName = "main-img",ImageName="plant-hire-haulage", ImageDescription = "Leibherr 726 GPS equiped dozer working at site"}'/>
    <div class="v-center-outer background-gradient">
        <div class="v-center-middle ml-img-overlay">
            <div class="v-center-inner">
                <h1 class="img-overlay-title">Plant Hire</h1>
                <p class="img-overlay-text">
                    Providing excellent plant hire services for over 30 years
                </p>
                <a href="@ConfigurationManager.AppSettings["Contact"]?subject=plant-hire" class="btn btn-blue img-overlay-btn"><i class="fas fa-envelope pr-2"></i>Plant Hire Enquiry</a>
            </div>
        </div>
    </div>
</div>
<div class="page-with-sidebar-container">
    <div class="page-with-sidebar-main">
        <div class="row">
            <div class="left-right-padding">
                <nav aria-label="breadcrumb" class="mt-4">
                    <ol class="breadcrumb pl-0">
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["Home"]">Home</a></li>
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["HaulageServices"]">Haulage</a></li>
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["PlantServices"]">Plant Services</a></li>
                        <li class="breadcrumb-item active"><a href="#">Plant Hire</a></li>
                    </ol>
                    <hr class="mb-0" />
                </nav>
                <div class="top-bottom-padding">
                    <h2 class="f1 body-title">Plant Hire</h2>
                    <p>
                        Rory J Holbrook Ltd offer crushers and screeners for any requirements you may have, big or small.
                        <br />
                        Our simple hiring process can be broken down into just four easy steps. The machine hire, the transport to the site, the setup and the experienced operator.
                        <br /><br />
                        All this can be put into one weekly price for you so you know exactly where the budget will be.
                        <br />
                        You'll also have excellent support if something happens to go wrong while the machine is on hire we're dedicated to making sure you get the job well done and as smoothly as possible.
                        <br /><br />
                        We offer nationwide loading shovel hire. Our unique approach enables us to offer anything from a week-to-week hire, rolling 6 or 12 month hire or fixed contract hire agreements.
                        <br /><br />
                        The machines are equipped to work within most applications with options of standard general, side tipping, high tipping or grapple buckets.
                        Most loading shovels have hydraulic quick hitches to allow quick exchange of attachments.
                        <br /><br />
                        Whether its for an <a href="@ConfigurationManager.AppSettings["AggregateSupply"]">aggregate</a> job or the hardest <a href="@ConfigurationManager.AppSettings["MaterialRemovalServices"]">waste application</a>, we are ready and have loading shovel packages to suit. Just <a href="/contact?subject=plant-hire">get in touch</a> to discuss this.
                    </p>
                    <h2 class="body-title">
                        Available Plant
                    </h2>
                    <div class="text-right">
                         <a class="btn btn-green btn-lg mb-3 mr-3" href="@ConfigurationManager.AppSettings["Contact"]?subject=plant-hire"><i class="fas fa-envelope pr-2"></i>Plant Hire Enquiry</a>
                    </div>
                    <div class="available-plants mb-3">
                        <div id="plant-3-way-screener" class="plant-container">
                            @await Component.InvokeAsync("TileSnippet", new TileSnippetViewComponent.TileSnippetViewModel
                            {
                                ImagePath = "mcclowskey-3-way-screener",
                                ImageDescription = "McCloskey 3 way split screener screening recycled aggregates",
                                Title = "3 Way Screener",
                                TileStyleEnum = (int)TileStyles.TextAbove,
                            })
                        </div>
                        <div id="plant-jaw-crusher" class="plant-container">
                            @await Component.InvokeAsync("TileSnippet", new TileSnippetViewComponent.TileSnippetViewModel
                            {
                                ImagePath = "mcCloskey-j45-jaw-crusher",
                                ImageDescription = "mcCloskey j45 jaw crusher in action",
                                Title = "Jaw Crusher",
                                TileStyleEnum = (int)TileStyles.TextAbove,
                            })
                        </div>
                        <div id="plant-wheel-loader" class="plant-container">
                             @await Component.InvokeAsync("TileSnippet", new TileSnippetViewComponent.TileSnippetViewModel
                            {
                                ImagePath = "wheel-loader-haulage",
                                ImageDescription = "Doosan DL450 and DL480 in Norfolk site",
                                Title = "Wheel Loader - Varying Sizes",
                                ButtonLink = "",
                                TileStyleEnum = (int)TileStyles.TextAbove,
                            })
                        </div>
                        <div id="plant-22-tonne-excavator" class="plant-container">
                            @await Component.InvokeAsync("TileSnippet", new TileSnippetViewComponent.TileSnippetViewModel
                            {
                                ImagePath = "22-tonne-excavator",
                                ImageDescription = "22 tonne luigong 922 demo spec",
                                Title = "22 Tonne Excavator",
                                ButtonLink = "",
                                TileStyleEnum = (int)TileStyles.TextAbove,
                            })
                        </div>
                        <div id="plant-bulldozer" class="plant-container">
                            @await Component.InvokeAsync("TileSnippet", new TileSnippetViewComponent.TileSnippetViewModel
                            {
                                ImagePath = "bulldozer-gps-equipped",
                                ImageDescription = "GPS equipped bulldozer plant for hire",
                                Title = "Bulldozer - GPS Equipped",
                                ButtonLink = "",
                                TileStyleEnum = (int)TileStyles.TextAbove,
                            })
                        </div>
                        <div id="plant-articulated-dump-truck" class="plant-container">
                            @await Component.InvokeAsync("TileSnippet", new TileSnippetViewComponent.TileSnippetViewModel
                            {
                                ImagePath = "articulated-dump-truck",
                                ImageDescription = "Leibherr Ta230 hauling materials",
                                Title = "Artciulated Dump Truck",
                                ButtonLink = "",
                                TileStyleEnum = (int)TileStyles.TextAbove,
                            })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar bg-light-light-blue">
        @await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
        {
            SnippetTypeEnum = (int)Enums.SnippetTypes.Sidebar,
            CurrentPage = "planthire",
            ParentPage = "haulage",
            CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.LightBlue,
            Title = "See Our Other Haulage Services"
        })
        @await Component.InvokeAsync("NewsSnippet", new { snippetTypeEnum = (int)Enums.SnippetTypes.Sidebar, numberOfArticles = 2, cssStyleEnum = (int)Enums.CssStyles.LightBlue})
    </div>
</div>
<div class="bg-blue">
    <div class="left-right-padding top-bottom-padding">
        <h4 class="text-white">We are proud to work alongside industry-leaders and to work to the highest standards of the industry.</h4>
        <hr />
        <div class="row">
            <partial name="partials/sliders/_standardsandpartnerssliders" model="@(int)Enums.Variations.Variation1" />
        </div>
    </div>
</div>
@await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
{
    SnippetTypeEnum = (int)Enums.SnippetTypes.FullBottomBar,
    CurrentPage = "",
    ParentPage = "construction",
    CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.Dark,
    Title = "We Also Offer Construction Services"
})
@section scripts {
    <script>
        @{
            if(Model.PlantType != null && Model.PlantType != ""){
                @:scrollToElement("#plant-@Model.PlantType",null,-180,true);
            }
        }
    </script>
}

Pages/Haulage/PlantServices.cshtml
@page "/plant-services"
@using RJHWebsite.Enums
@using System.Configuration
@{
    ViewBag.NavButtonNames = "haulage-services-nav-btn,plant-services-nav-btn";
    ViewBag.Title = "Plant Services";
}
@section head{
    <meta name='description' content="Our low loaders and plant are available to hire at competitive prices. From 3 way screeners to excavators, we have what you need." />
}
<partial name='partials/_image' model='new RJHWebsite.Models.ImageModel(){ ImageClassName = "main-img",ImageName="plant-services-haulage", ImageDescription = "Rory J Holbrook DL450 Plant on display"}'/>
<div class="page-name">
    <h1>Plant Services</h1>
</div>
<div class="page-with-sidebar-container">
    <div class="page-with-sidebar-main">
        <div class="left-right-padding">
            <div class="row">
                <nav aria-label="breadcrumb" class="mt-4">
                    <ol class="breadcrumb pl-0">
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["Home"]">Home</a></li>
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["HaulageServices"]">Haulage</a></li>
                        <li class="breadcrumb-item active"><a href="#">Plant Services</a></li>
                    </ol>
                    <hr class="mb-0" />
                </nav>
            </div>
            <div class="top-bottom-padding">
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_planthiretile" model="@(int)TileStyles.SquareZoom" />
                </div>
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_lowloadertile" model="@(int)TileStyles.SquareZoom" />
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar bg-light-light-grey">
        @await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
        {
            SnippetTypeEnum = (int)Enums.SnippetTypes.Sidebar,
            CurrentPage = "",
            ParentPage = "haulage",
            CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.LightGrey,
            Title = "See All Haulage Services"
        })
    </div>
</div>
 @await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
{
    SnippetTypeEnum = (int)Enums.SnippetTypes.FullBottomBar,
    CurrentPage = "",
    ParentPage = "construction",
    CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.Dark,
    Title = "See All Construction Services"
})
@await Component.InvokeAsync("NewsSnippet", new { snippetTypeEnum = (int)Enums.SnippetTypes.FullBottomBar, numberOfArticles = 2, cssStyleEnum = (int)Enums.CssStyles.LightBlue })

Pages/Haulage/RailHaulage.cshtml
@page "/rail-haulage"
@using RJHWebsite.Enums
@using System.Configuration
@{
    ViewBag.NavButtonNames = "haulage-services-nav-btn,rail-haulage-services-nav-btn";
    ViewBag.Title = "Rail Haulage Services";
}
@section head{
    <meta name='description' content="With our extensive rail haulage services and with railhead locations situated throughout East Anglia, we can continue to supply aggregates to the UK." />
}
<partial name='partials/_image' model='new RJHWebsite.Models.ImageModel(){ ImageClassName = "main-img",ImageName="railheads-haulage", ImageDescription = "Unloading material supplies through rail infrastructure to grab lorry"}' />
<div class="page-name">
    <h1>Rail Haulage</h1>
</div>
<div class="page-with-sidebar-container">
    <div class="page-with-sidebar-main">
        <div class="left-right-padding">
            <div class="row">
                <nav aria-label="breadcrumb" class="mt-4">
                    <ol class="breadcrumb pl-0">
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["Home"]">Home</a></li>
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["HaulageServices"]">Haulage</a></li>
                        <li class="breadcrumb-item active"><a href="#">Rail Haulage</a></li>
                    </ol>
                    <hr class="mb-0" />
                </nav>
            </div>
            <div class="top-bottom-padding">
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_railheadstile" model="@(int)TileStyles.SquareZoom" />
                </div>
                <div class="nav-page-tile-container">
                    <partial name="partials/construction/_aggregatesuppliestile" model="@(int)TileStyles.SquareZoom" />
                </div>
                <div class="nav-page-tile-container">
                    <partial name="partials/locations/_locationstile" model="@(int)TileStyles.SquareZoom" />
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar bg-light-light-grey">
        @await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
        {
            SnippetTypeEnum = (int)Enums.SnippetTypes.Sidebar,
            CurrentPage = "",
            ParentPage = "construction",
            CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.LightGrey,
            Title = "Explore Our Construction Services"
        })
    </div>
</div>
@await Component.InvokeAsync("NewsSnippet", new { snippetTypeEnum = (int)Enums.SnippetTypes.FullBottomBar, numberOfArticles = 2, cssStyleEnum = (int)Enums.CssStyles.LightBlue })

Pages/Haulage/RoadHaulage.cshtml
@page "/road-haulage"
@using RJHWebsite.Enums
@using System.Configuration
@{
    ViewBag.NavButtonNames = "haulage-services-nav-btn,road-haulage-services-nav-btn";
    ViewBag.Title = "Road Haulage Services";
}
@section head{
    <meta name='description' content="Our specialist road haulage services include a selection of vehicle hire from tippers to grabs. Articulated and 8 Wheelers are available." />
}
<partial name='partials/_image' model='new RJHWebsite.Models.ImageModel(){ ImageClassName = "main-img",ImageName="all-rory-lorries", ImageDescription = "Collection of rorys 8 wheeler and articulated lorries lined up in Norwich"}' />
<div class="page-name">
    <h1>Road Haulage</h1>
</div>
<div class="page-with-sidebar-container">
    <div class="page-with-sidebar-main">
        <div class="left-right-padding">
            <div class="row">
                <nav aria-label="breadcrumb" class="mt-4">
                    <ol class="breadcrumb pl-0">
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["Home"]">Home</a></li>
                        <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["HaulageServices"]">Haulage</a></li>
                        <li class="breadcrumb-item active"><a href="#">Road Haulage</a></li>
                    </ol>
                    <hr class="mb-0" />
                </nav>
            </div>
            <div class="top-bottom-padding">
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_tipperhiretile" model="@(int)TileStyles.SquareZoom" />
                </div>
                <div class="nav-page-tile-container">
                    <partial name="partials/haulage/_grabhiretile" model="@(int)TileStyles.SquareZoom" />
                </div>
            </div>
        </div>
    </div>
    <div class="sidebar bg-light-light-grey">
        @await Component.InvokeAsync("OtherPagesSnippet", new RJHWebsite.Models.OtherPagesSnippetModel
        {
            SnippetTypeEnum = (int)Enums.SnippetTypes.Sidebar,
            CurrentPage = "",
            ParentPage = "construction",
            CssStyleEnum = (int)RJHWebsite.Enums.CssStyles.LightGrey,
            Title = "Explore Our Construction Services"
        })
    </div>
</div>
@await Component.InvokeAsync("NewsSnippet", new { snippetTypeEnum = (int)Enums.SnippetTypes.FullBottomBar, numberOfArticles = 2, cssStyleEnum = (int)Enums.CssStyles.LightBlue })