Pages/News/MdigAndRJH.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RJHWebsite.Pages.News
{
    public class MdigAndRJHModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/News/News.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//using Microsoft.AspNetCore.Mvc;
using System.IO;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RJHWebsite.Models;
using Newtonsoft.Json;

namespace RJHWebsite.Pages.News
{
    public class NewsModel : PageModel
    {
        public List<NewsInformationModel> NewsInformationModel { get; set; }
        public void OnGet()
        {
            string newsJson = System.IO.File.ReadAllText("news-articles-v1.0.json").ToString();
            NewsInformationModel = JsonConvert.DeserializeObject<List<NewsInformationModel>>(newsJson);
            NewsInformationModel = NewsInformationModel.OrderByDescending(r => Convert.ToDateTime(r.PublishedDate)).ToList();
            //return View("NewsSnippet", newsInfo);
        }
    }
}

Pages/Shared/Components/NewsPage/NewsPageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RJHWebsite.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace RJHWebsite.Pages.Shared.Components.NewsPage
{
    public class NewsPageViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string newsArticlePageName)
        {
            string newsJson = File.ReadAllText("news-articles-v1.0.json").ToString();
            List<NewsInformationModel> newsInfo = JsonConvert.DeserializeObject<List<NewsInformationModel>>(newsJson);
            return View("NewsPage", newsInfo.Where(r=>r.PageName == newsArticlePageName).FirstOrDefault());
        }
    }
    
}

Pages/News/DCRailSuccess.cshtml
@page "/news/dc-rail-success"
@{
    ViewBag.Title = "DC Rail Success";
    ViewBag.NavButtonNames = "news-nav-btn";
}
}
@section head{
    <meta name="robots" content="noindex">
}
@await Component.InvokeAsync("NewsPage", new { newsArticlePageName = "dc-rail-success"})

Pages/News/MdigAndRJH.cshtml
@page "/news/mdig-and-rjh"
@{
    ViewBag.Title = "RJH and MDig Partnership";
    ViewBag.NavButtonNames = "news-nav-btn";
}
@section head{
    <meta name="robots" content="noindex">
}
@await Component.InvokeAsync("NewsPage", new { newsArticlePageName = "mdig-and-rjh"})

Pages/News/NewDaf8x4.cshtml
@page "/news/new-daf-8x4"
@{
    ViewBag.Title = "New DAF 8x4";
    ViewBag.NavButtonNames = "news-nav-btn";
}
@section head{
    <meta name="robots" content="noindex">
}
@await Component.InvokeAsync("NewsPage", new { newsArticlePageName = "new-daf-8x4"})

Pages/News/News.cshtml
@page "/news"
@using RJHWebsite.Enums;
@using System.Configuration
@model RJHWebsite.Pages.News.NewsModel
@{
    ViewBag.Title = "Latest News";
    ViewBag.NavButtonNames = "news-nav-btn";
}
@section head{
    <meta name="robots" content="noindex">
}
<div class="left-right-padding">
    <div class="row">
        <nav aria-label="breadcrumb" class="mt-4">
            <ol class="breadcrumb pl-0">
                <li class="breadcrumb-item"><a href="@ConfigurationManager.AppSettings["Home"]">Home</a></li>
                <li class="breadcrumb-item active"><a href="@ConfigurationManager.AppSettings["News"]">News</a></li>
            </ol>
            <hr class="mb-0" />
        </nav>
    </div>
    <div class="top-bottom-padding">
        <div class="row row-plr-0">
            @foreach(var newsArticle in Model.NewsInformationModel)
            {
                <div class="col-md-6 col-12 mb-4">
                    <div class="all-news-individual-container">
                        <h3 class="news-page-title mb-3">@newsArticle.Title</h3>
                        <partial name='partials/_image' model='new RJHWebsite.Models.ImageModel(){ ImageClassName = "main-news-page-img",ImageName=newsArticle.ImagePath+"-md", ImageDescription = newsArticle.ImageDescription, IncludeOtherSizes = false}'/>
                        <p><i>Source: <a href="@newsArticle.SourceLink" target="_blank">@newsArticle.SourceName</a></i></p>
                        <p><i>@newsArticle.PublishedDate</i></p>
                        <br />
                        <p class="news-right-text">
                            @(Html.Raw(System.Web.HttpUtility.HtmlDecode(newsArticle.Body.Substring(0, 200))))...
                        </p>
                        <a class="mt-3 btn btn-blue" href="/news/@newsArticle.PageName"><p>Read More</p></a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Pages/News/SurfaceDressingInnovation.cshtml
@page "/news/surface-dressing-innovation"
@{
    ViewBag.Title = "Surface Dressing Innovation";
    ViewBag.NavButtonNames = "news-nav-btn";
}
@section head{
    <meta name="robots" content="noindex">
}
@await Component.InvokeAsync("NewsPage", new { newsArticlePageName = "surface-dressing-innovation"})

Pages/News/UKFirstForRJH.cshtml
@page "/news/uk-first-for-rjh"
@{
    ViewBag.Title = "UK First For RJH";
    ViewBag.NavButtonNames = "news-nav-btn";
}
@section head{
    <meta name="robots" content="noindex">
}
@await Component.InvokeAsync("NewsPage", new { newsArticlePageName = "uk-first-for-rjh"})